<a href="https://colab.research.google.com/github/shinchan75034/Techniques/blob/main/Numpy_Array_Skipping_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy array slicing by skipping
`numpy` array slicing can get very confusing. There are so many different notations that can be used to do all sorts of tricks. With array slicing, that bag of tricks just never stop to confuse me. 

Have you see double colons `::` being used in `numpy` array slicing? When you see it, think of it as a way to select records in the array by skipping at certain intervals. Now you just need to know how it works. We will start with an array of 20 records, each with five elements.

In [ ]:
import numpy as np
r = np.arange(100)
r.resize((20,5))
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

Take a look at what this does:

In [ ]:
r[1::2]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

`1` indicates selecting for the second record (`numpy` index starts with 0), and `2` indicates skipping next record and select the following record. This pattern repeats until the end of the array.

Let's try another one: 

In [ ]:
r[2::4]

array([[10, 11, 12, 13, 14],
       [30, 31, 32, 33, 34],
       [50, 51, 52, 53, 54],
       [70, 71, 72, 73, 74],
       [90, 91, 92, 93, 94]])

`2` indicates selecting the third record, and 4 indicates skipping next three records and select the following record. This repeats until the end of the array.

Now let's see what this one is doing:

In [ ]:
r[:, 1::3]

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19],
       [21, 24],
       [26, 29],
       [31, 34],
       [36, 39],
       [41, 44],
       [46, 49],
       [51, 54],
       [56, 59],
       [61, 64],
       [66, 69],
       [71, 74],
       [76, 79],
       [81, 84],
       [86, 89],
       [91, 94],
       [96, 99]])

Single colon `:` indicates every row is selected. `1::3` indicates that from the second element in each record, skip next two elements and select the following element. This shows that you may use double colon `::` to select elements by skipping within a `numpy` record.